[project]
name = "distribits-2025"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "gitpython>=3.1.45",
    "jupyter>=1.1.1",
    "pandas>=2.3.3",
    "pygithub>=2.8.1",
    "requests>=2.32.5",
]
