project:
  type: website
  output-dir: ../docs

website:
  title: "Maintaining large datasets at scale"
  navbar:
    left:
      - href: https://github.com/effigies/distribits-2025
        text: Github page

format:
  html:
    theme: darkly
    css: styles.css

